### PR TITLE
changed name of DroMel map and added liftover documentation

### LINKED ISSUE #695: documenting how to run`liftOver_comeron2012.py` for the DroMel maps that will be uploaded to AWS
The following run command will automatically be saved as a part of the `README` file which @andrewkern will be uploading to AWS, along with revised maps for DroMel. All files will be contained within the `comeron2012_maps.tar.gz` tarball. Is there a need or desire to document this somewhere else, in the maintenance section of the documentation perhaps?

```
 python liftOver_comeron2012.py \
    --winLen 1000 \
    --gapThresh 1000000 \
    --useAdjacentAvg \
    --retainIntermediates
```

### PR DESCRIPTION
**Pull request by jradrion**
- changed the name of the DroMel map created by `/maintenance/liftover_comeron2012.py`
- added the new genetic map to `DroMel/__init__.py` 
- added documentation about the liftover maintenance code

fixes #695

### CODE REVIEW

**Comment by jradrion** [comment]
This should not be merged until we can get the new map uploaded to AWS.

**Comment by jradrion** [comment]
OK, I definitely messed something up since a bunch of checks are failing. I'll try to fix that ASAP.

**Comment by grahamgower** [comment]
Thanks for writing this up @jradrion! The pre-commit tests are failing because there are some spaces at the ends of some lines. I think these will be trimmed off automatically if you have `pre-commit` installed under your repository. Let me know if they don't get trimmed (the pre-commit configuration could need changing). The other tests are failing just because the url points to a non existent file, which I guess is expected if the files haven't been uploaded. The error message could be better though, so I'll open an issue to track that.

**Comment by jradrion** [comment]
@grahamgower 
> The pre-commit tests are failing because there are some spaces at the ends of some lines. I think these will be trimmed off automatically if you have pre-commit installed under your repository. Let me know if they don't get trimmed (the pre-commit configuration could need changing)

I have pre-commit installed but I'm not sure exactly what is going on. Here's what happens if I run `pre-commit run` on the staged file `/docs/development.rst`:

```
(tf2.1) jadrion@sesame:~/soft/popgensims/stdpopsim/docs$ pre-commit run
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
blacken-docs.............................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/development.rst

Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
Check for merge conflicts................................................Passed
Mixed line ending........................................................Passed
```

**Comment by grahamgower** [comment]
It looks like the pre-commit process fixed the trailing whitespace. If you run `git status` it should show the *.rst file as having modifications. So I think you now need to `git add` that modified file, and `git commit` the changes.

**Comment by jradrion** [comment]
Just curious, why would it not have auto-fixed the trailing whitespace the first time I ran `git commit`?

**Comment by grahamgower** [comment]
That, I cannot answer. :)

**Comment by andrewkern** [comment]
@jradrion and uploaded the lifted over maps to aws manually, and now are rerunning the tests

**Review by andrewkern — APPROVED** [review]

**Pull request merged**
