### PR TITLE
Oo a nea ext puls demo

### PR DESCRIPTION
**Pull request by LeonardoIasi**
Additional HomSap demography of an simple OoA with Nenadertal introgression following Iasi et al. 2021 including the extended admixture pulse with a duration of 800 generations.

### CODE REVIEW

**Comment by grahamgower** [comment]
Hi @LeonardoIasi! Thanks for the model addition! I haven't gone through the details, but it looks like there are a few code paths that aren't used in your nested `extended_pulse()` function. Given that you're calling the function only once with fixed values, maybe you could just `assert` that the conditions for these code paths dont happen and then remove that code?

**Comment by LeonardoIasi** [comment]
Hello, 
yes the function has some if statements. But true since the parameters will not vary the function does not need to check them. I'll change the code and  commit again. Thanks

**Review by grahamgower — APPROVED** [review]
LGTM.

**Comment by grahamgower** [comment]
@LeonardoIasi, would you please open an issue to track the QC of the model implementation as per the dev docs? https://stdpopsim.readthedocs.io/en/latest/development.html#demographic-model-review-process

**Pull request merged**
