### PR TITLE
Don't use scipy and pandas for OutOfAfricaExtendedNeandertalAdmixture…

### PR DESCRIPTION
**Pull request by grahamgower**
…Pulse_3I21

* Scipy was being used for the Gamma PDF, which has been reimplemented using the math.gamma() function.
* Pandas use here was unnecessary, so has been removed.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks @grahamgower - agreed with all the above!

**Comment by petrelharp** [comment]
Me too - seems tricky!

**Comment by jeromekelleher** [comment]
We should totally not be importing the qc models at runtime unless specifically requested - would be happy to help with workarounds to get them out of the ``import stdpopsim`` code flow

**Comment by grahamgower** [comment]
> We should totally not be importing the qc models at runtime unless specifically requested - would be happy to help with workarounds to get them out of the `import stdpopsim` code flow

I think I'd rather have that as a separate PR, and I've opened #1418 to discuss/track.

Maybe for this PR, you'd be happy to look at the CI runs and satisfy yourself that I haven't changed the demographic model (the QC test still passes)? I can then push another commit making the analogous change to remove scipy/pandas from the QC model.

**Comment by grahamgower** [comment]
One additional point: `time python -c 'import stdpopsim'` takes about 1 second; after removing pandas/scipy from the import path, this drops to 500 ms. Loading the QC models (or not) makes negligible difference to import time once pandas/scipy is removed.

**Comment by grahamgower** [comment]
This is good to go now @jeromekelleher.

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Pull request merged**
