### PR TITLE
major edits in section for adding species (incl. moving it up)

### PR DESCRIPTION
**Pull request by igronau**
This is an initial version of my edits. I have some more edits I'd like to make, but I'll do those later

### CODE REVIEW

**Comment by nspope** [comment]
Thanks a bunch @igronau! 

It looks like the line endings in `development.rst` have changed (Windows uses CRLF instead of LF) which causes the CI checks to fail -- if you [install the pre-commit hooks](https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#pre-commit-checks) (run `pre-commit install` in your local copy of the repository), then these hooks will fix annoying formatting issues like line endings whenever you commit. If issues are detected, the hooks will modify the files and abort the commit; so you'll have to do `git add .; git commit -m <message>` again. Alternatively, I can do this when you're done making your edits.

Also, the line ending thing makes the diff shown by github (under 'Files changed' tab) look like the entire file has changed rather than just particular lines. To make it easier to review (I just learned) you can click on the gear next to "Jump to" and check "Hide whitespace changes".

**Comment by igronau** [comment]
@nspope It's because of the editor I used. I'll fix this in my next commit.

**Comment by petrelharp** [comment]
Hi, @igronau - can we get these updates?

**Comment by petrelharp** [comment]
Are you addressing #1374 here, by the way?

**Comment by igronau** [comment]
I submitted a separate PR (#1397) with a cleaner version that can be more easily reviewed. Please continue discussion there.

**Comment by nspope** [comment]
Superceded by #1397.

**Pull request closed without merging**
