### PR TITLE
pin python 3.8

### PR DESCRIPTION
**Pull request by David-Peede**
pinned python to version 3.8 in rtd-conda-environment.yml

### CODE REVIEW

**Comment by petrelharp** [comment]
Why do we need to do this?

**Comment by petrelharp** [comment]
Oh, never mind: #622

**Comment by grahamgower** [comment]
Looks good! Annoyingly, the rtd build doesn't get kicked off during continuous integration. So let's merge and see what happens...

**Comment by David-Peede** [comment]
Looks like it worked!

**Pull request merged**
