### PR TITLE
Changed parameters for rice

### PR DESCRIPTION
**Pull request by ornobalam**
Flagging @minesrebollo

### CODE REVIEW

**Comment by nspope** [comment]
Thanks @ornobalam! It looks like the [precommit hooks](https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#github-workflow) need to be installed/run, to auto-fix formatting in your changes. Let me know if you run into issues or have questions.

**Comment by nspope** [comment]
Hi @ornobalam, I noticed you opened a new PR related to fixing the pre-commit stuff. Instead, I'd suggest modifying this current PR. Here's a suggestion as to how to go about doing that:

Navigate to your local copy of stdpopsim, checkout your feature branch, and make sure that it's at the right place
```bash
git checkout add_rice
git log | head
#commit ab630395d3084b277c0c9de50ee250c9b8d941dd (HEAD -> rice-changes)
#Author: ornobalam <oa832@nyu.edu>
#Date:   Wed May 17 15:21:36 2023 -0400
#
#    changed parameter coding
```

Install the pre-commit hooks and force them to run (this requires that you've installed the pre-commit module and other development dependencies, by `python3 -m pip install -r requirements/development.txt`). 
```bash
pre-commit install
pre-commit run --all-files
#black....................................................................Failed
#- hook id: black
#- files were modified by this hook
#
#reformatted stdpopsim/catalog/OrySat/demographic_models.py
#All done! ✨ 🍰 ✨
#1 file reformatted, 174 files left unchanged.
# <snip>
```

So, the `black` tool modified a file to fix formatting issues, and this now needs to be committed and pushed to github:
```
git add .
git commit -m 'Fix pre-commit black'
git push
```

Hope that helps!

**Comment by ornobalam** [comment]
@nspope, Hi! Thanks so much, that was really helpful. I think I was able to run all the steps successfully.

**Comment by nspope** [comment]
Merging-- test failures are because the macos-10.15 runners have been retired.

**Pull request merged**
