### PR TITLE
Adding the HapMap and deCode HomSap recombination maps lifted over to GRCh38

### PR DESCRIPTION
**Pull request by saurabhbelsare**
This is to complete https://github.com/popsim-consortium/stdpopsim/issues/543 

The lifted over genetic maps have been added to AWS and the corresponding details have been updated in HomSap/genetic_maps.py 

New map options HapMapII_GRCh38 and DeCodeSexAveraged_GRCh38 have been created in addition to the original HapMapII_GRCh37 and DeCodeSexAveraged_GRCh36.

### CODE REVIEW

**Comment by saurabhbelsare** [comment]
Sorry, I don't know why there is a previous commit for the Papio Anubis genome here, I did that in a separate branch and am not sure why it is being included here. It has been independently completed and merged in a separate PR.

**Comment by andrewkern** [comment]
looks like you started this off of a very stale branch. can you restart this PR from a fresh pull from main please?

**Comment by saurabhbelsare** [comment]
Hi Andy, I've created a new PR with a fresh pull from main. That should be up to date, and doesn't have my old commit either. Can this PR just be deleted? Thanks.

**Comment by andrewkern** [comment]
yes i'll close this down

**Pull request closed without merging**
