### PR TITLE
Changelog for 0.1.2.

### LINKED ISSUE #551: Write changelog
Need to write a changelog for 0.1.2.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Closes #551

I'll release tomorrow assuming there's no hiccups.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Quite a lot in here, so it would be good to get some eyes on the changelog to make sure I didn't miss anything (apologies if I did!)

We should get into the habit of updating the changelog as we go from here I think - it's quite error prone (not to mention tedious) going back through the PR list.

**Comment by grahamgower** [comment]
The PonAbe addition seems to be missing. Also, perhaps we could have separate headings for "new species", "new demographic models", and "new features"?

**Comment by jeromekelleher** [comment]
> The PonAbe addition seems to be missing. Also, perhaps we could have separate headings for "new species", "new demographic models", and "new features"?

Good call on both counts, should be fixed now.

**Comment by ndukler** [comment]
Dunno if we mention it because it's internal but we also added a QC check for sampling times in PR #429

**Comment by ndukler** [comment]
Also I noticed that generation time was set to 1 for generics as per #459 although this was largely for the SLiM engine so again I don't know it it should be added

**Comment by agladstein** [comment]
What belongs in a changelog? Because I'm seeing a lot of little commits that don't seem to fit into what you have already in the changelog.

**Comment by jeromekelleher** [comment]
> What belongs in a changelog? Because I'm seeing a lot of little commits that don't seem to fit into what you have already in the changelog.

I think a changelog should contain the things that a user needs to know about that are *different to the last release*. So, all the stuff that happened on the slim engine isn't relevant because it didn't exist in the last release. It's a quick summary that a user can look at and know (a) is there cool new stuff that I should be using and (b) is this release going to break my code.

**Comment by jeromekelleher** [comment]
> Dunno if we mention it because it's internal but we also added a QC check for sampling times in PR #429

This is more internal development infrastructure to me @ndukler, and not something that an end-user needs to know about.

**Pull request merged**
