### PR TITLE
lint fixes for maintenance folder

### PR DESCRIPTION
**Pull request by grahamgower**
See #615

### CODE REVIEW

**Comment by grahamgower** [comment]
Oh no. What's happened here....?

**Comment by platipo** [comment]
I think it may be linked to my worry of the deterministic builds, it seems that a `numpy` is missing

**Comment by platipo** [comment]
Can you try to pass this as the `requirements/development.txt`
```
alabaster==0.7.12         # via sphinx
appdirs==1.4.4            # via -r ./requirements/development.txt
attrs==20.2.0             # via -r ./requirements/development.txt, jsonschema, pyslim, tskit
babel==2.8.0              # via sphinx
certifi==2020.6.20        # via requests
chardet==3.0.4            # via requests
codecov==2.1.10           # via -r ./requirements/development.txt
coverage==5.3             # via -r ./requirements/development.txt, codecov
docutils==0.16            # via sphinx
flake8==3.8.4             # via -r ./requirements/development.txt
h5py==2.10.0              # via tskit
humanize==3.0.1           # via -r ./requirements/development.txt, kastore
idna==2.10                # via requests
imagesize==1.2.0          # via sphinx
importlib-metadata==2.0.0  # via flake8, jsonschema
jinja2==2.11.2            # via sphinx
jsonschema==3.2.0         # via tskit
kastore==0.3.1            # via -r ./requirements/development.txt, pyslim
markupsafe==1.1.1         # via jinja2
mccabe==0.6.1             # via flake8
msprime==0.7.4            # via -r ./requirements/development.txt, pyslim
nose==1.3.7               # via -r ./requirements/development.txt
numpy==1.19.2             # via h5py, kastore, msprime, pyslim, tskit
packaging==20.4           # via sphinx
pycodestyle==2.6.0        # via flake8
pyflakes==2.2.0           # via flake8
pygments==2.7.1           # via sphinx
pyparsing==2.4.7          # via packaging
pyrsistent==0.17.3        # via jsonschema
pyslim==0.403             # via -r ./requirements/development.txt
pytz==2020.1              # via babel
requests==2.24.0          # via codecov, sphinx
setuptools-scm==4.1.2     # via -r ./requirements/development.txt
six==1.15.0               # via h5py, jsonschema, packaging
snowballstemmer==2.0.0    # via sphinx
sphinx-argparse==0.2.5    # via -r ./requirements/development.txt
sphinx-issues==1.2.0      # via -r ./requirements/development.txt
sphinx-rtd-theme==0.5.0   # via -r ./requirements/development.txt
sphinx==3.2.1             # via -r ./requirements/development.txt, sphinx-argparse, sphinx-issues, sphinx-rtd-theme, sphinxcontrib-programoutput
sphinxcontrib-applehelp==1.0.2  # via sphinx
sphinxcontrib-devhelp==1.0.2  # via sphinx
sphinxcontrib-htmlhelp==1.0.3  # via sphinx
sphinxcontrib-jsmath==1.0.1  # via sphinx
sphinxcontrib-programoutput==0.16  # via -r ./requirements/development.txt
sphinxcontrib-qthelp==1.0.3  # via sphinx
sphinxcontrib-serializinghtml==1.1.4  # via sphinx
svgwrite==1.4             # via tskit
tskit==0.3.2              # via msprime, pyslim
urllib3==1.25.10          # via requests
zipp==3.3.1               # via importlib-metadata
```

**Comment by grahamgower** [comment]
Hey @platipo. In some new dependencies were added by #560, which was merged just before your PR. I guess that is relevant too?

**Comment by platipo** [comment]
Yes, it took a brief look and I think so!

**Comment by platipo** [comment]
I managed to mak build-deps pass thanks to a workaround:

https://github.com/popsim-consortium/stdpopsim/blob/834a5317ca48b871437a692d2b2338e2cb46478f/.circleci/config.yml#L64-L66

and

https://github.com/popsim-consortium/stdpopsim/blob/834a5317ca48b871437a692d2b2338e2cb46478f/.circleci/config.yml#L72-L77

The missing numpy should be reported to the scikit-allel

**Comment by grahamgower** [comment]
Cool, thanks @platipo!

**Comment by grahamgower** [comment]
FYI, it looks like scikit-allel is already aware they have a chicken-and-egg build problem: https://github.com/cggh/scikit-allel/issues/248

**Pull request merged**
