### PR TITLE
Vaquita QC

### PR DESCRIPTION
**Pull request by ckyriazis**
This includes QC for the vaquita species (#1525) and 2 epoch demographic model (#1530). I'm currently failing a strange test related to the parameter table for an AnaPla demographic model so hoping to get some help to figure out why. 

Its been a while since I've made any contributions to stdpopsim so apologies if I have messed anything up in the workflow...

### CODE REVIEW

**Review by petrelharp — APPROVED** [review]
Looks good to me - I don't see any issues! Let's just verify what's going on with CI before merging.

**Comment by petrelharp** [comment]
Oh this is because of #1537. Hm, let's see.

**Comment by petrelharp** [comment]
@andrewkern do you know how to clear `_test_cache/` for CI? Maybe if we just bump the cache number?

**Comment by petrelharp** [comment]
Ah I think we just needed a rebase

**Comment by petrelharp** [comment]
This looks good to me, shall we merge, @ckyriazis?

**Comment by ckyriazis** [comment]
yep sounds good!

**Pull request merged**
