### PR TITLE
Interactive notebooks on Binder

### PR DESCRIPTION
**Pull request by carjed**
reopen of #42 from a branch that is compatible with nbviewer. An example on Binder can be accessed at https://mybinder.org/v2/gh/carjed/stdpopsim/binder_setup. Note again that it might take a minute or two to launch, but this should resolve the 404 errors we were getting before.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This is **very** cool! I got a 503 error at the end, but I see no reason not to merge what we have here.

**Comment by carjed** [comment]
Where exactly is the 503 error showing up? Also, any suggestions for a good example or two to include in the default notebook? Right now I just copied the first few cells from `qc/homo_sapiens_qc/homo_sapiens.ipynb` as a placeholder

**Comment by jeromekelleher** [comment]
> Where exactly is the 503 error showing up? 

I got a 503 when it redirected to the JupyterHub. No suggestions for the default notebook at the moment, probably a good place to put some quick pointers once things have settled down.

**Comment by andrewkern** [comment]
where is this at currently @carjed? would love to merge this if things are working

**Comment by carjed** [comment]
Just confirmed that the Binder instance is launching with no hiccups and I can run code in the default notebook (https://github.com/popgensims/stdpopsim/blob/bd714c2cc60228207bbc585029d5bf7b85ac9eb6/index.ipynb)

This is based on a now-deprecated [QC notebook](https://github.com/popgensims/stdpopsim/blob/bd714c2cc60228207bbc585029d5bf7b85ac9eb6/qc/homo_sapiens_qc/homo_sapiens.ipynb) that @jgallowa07 created, so we should decide on a few toy analyses that would be a good demonstration of what one can do with the library. Is there anything from the analysis repo we can port over?

**Comment by andrewkern** [comment]
good question. nothing in notebook....

**Comment by jeromekelleher** [comment]
I think we should hold off on this a little bit until the code has gone through another round of refactoring and is close to release. We can write a notebook illustrating the features then.

**Comment by jeromekelleher** [comment]
We have a conda package now @carjed --- would you like to finish this up now? All we want in the notebook is a very simple example of the Python API in action. We can provide links to the tutorials for those who want to explore more.

**Comment by jeromekelleher** [comment]
superseded by #453

**Pull request closed without merging**
