### PR TITLE
Added honeybee

### PR DESCRIPTION
**Pull request by janaobsteter**
Added honeybee genome and species data

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks for this @janaobsteter, it'll be great to get this species into the catalog!

The PR is a bit messy right now though, unfortunately. You'll need to rebase following the instructions [here](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing)

Also, it looks like you have a lot of extra files in here too (like pycache binaries, etc), can you remove these please? (It might be simplest to copy the new source files into a clean branch and start a different PR)

**Comment by janaobsteter** [comment]
Jerome, hi!

Yes, I know this is messy and I have to remove the files - but I am still
learning about how git works (usually I just push things until it works😅)
so I have to spend a bit more time on learning it.
So, I should create a new branch, copy the new files there, remove the old
branch, and then add and commit just the new files on the new branch?

Also, I am not sure whether to create the PR at the beginning or once we
are a bit more confident in our files?

Sorry for this and thanks!
Jana

**Comment by jeromekelleher** [comment]
No worries at all Jana, we all get git stuff mixed up, thanks for contributing!

I think it would be simplest to copy the ApiMel files to a temporary directory, create a new feature branch, and then copy these files into the new feature branch. Something like

```
mkdir tmp
cp -R stdpopsim/catalog/ApiMel tests/test_ApiMel.py tmp
git fetch upstream
git checkout upstream/main
git checkout -b apimel-v2
mkdir stdpopsim/catalog/ApiMel
cp tmp/ApiMel/*.py  stdpopsim/catalog/ApiMel
cp tmp/test_ApiMel.py tests
git add stdpopsim/catalog/ApiMel/*.py  tests/test_ApiMel.py
git commit
```
should do it

**Comment by gregorgorjanc** [comment]
Great @janaobsteter happy to help. I just sorted BosTau. Onto ZeaMay now;)

**Comment by jeromekelleher** [comment]
Hi @janaobsteter - is this PR still relevant or should we close it?

**Comment by janaobsteter** [comment]
@Jerome Kelleher ***@***.***> , this PR is not relevant
anymore, since it was the first "failed" attempt. Thanks!

**Pull request closed without merging**
