### PR TITLE
C. elegans mutation map

### PR DESCRIPTION
**Pull request by attrna**
A PR connected to #904 and #910. The description of the parameters for _C. elegans_ is in #834

### CODE REVIEW

**Comment by petrelharp** [comment]
Hi, @attrna - I'm a bit confused, could you let me know what's going on here? Is `_species._add_mutation_map( )` implemented yet? And, it looks like you're adding more than just a mutation map here; should that supercede the CaeEle info that's already in the catalogue?

**Comment by petrelharp** [comment]
Okay, awesome - could you separate out the mutation map into a different PR, then?

**Comment by attrna** [comment]
Ok! Please could you tell me what is the best way to do it? Maybe I should just remove it somehow?

**Comment by attrna** [comment]
I mean the PR with the genetic map has been merged recently (#910), and I just need to upload the map from sesame to Amazon

**Comment by petrelharp** [comment]
Ah, ok, great! I've converted this to a "draft", and when we get in mutation maps can revisit this.

**Comment by andrewkern** [comment]
hey all-- the C. elegans map can now be found on AWS at the following link:
https://stdpopsim.s3.us-west-2.amazonaws.com/genetic_maps/CaeEle/rockman2009_maps.tgz

the URL in the catalog file should be updated to reflect this

**Comment by petrelharp** [comment]
Note that the recombination map that is in this PR is already in the catalog. And - I'm going to close this (we can open it again later).

**Pull request closed without merging**
