### PR TITLE
Update CI versions

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by petrelharp** [comment]
Ping me on slack if I should jump in here, @benjeffery - I may or may not notice what happens here. Godspeed!

**Comment by nspope** [comment]
The issue is that `tests/test_dfes.py::TestRegisterQCDFE::test_register_qc` assigns an object to be an attribute of itself, which causes the recursion issue. I'm completely puzzled as to why this hasn't surfaced before, but is pretty easy to fix by changing the test to:
```python
    def test_register_qc(self):
        dfe = self.make_dfe("test")
        dfe_two = self.make_dfe("test")
        dfe.register_qc(dfe_two)   # was previously dfe.register_qc(dfe)                                                                        
        assert dfe.qc_dfe == dfe_two
```

**Comment by nspope** [comment]
If you rebase on main hopefully that'll fix the error here, @benjeffery

**Comment by petrelharp** [comment]
Rebased.

**Comment by petrelharp** [comment]
Now biopython is failing to compile?!?!

**Comment by nspope** [comment]
It's a Biopython version thing-- the installed version is using CPython's deprecated unicode API, which was removed in python 3.12

**Comment by benjeffery** [comment]
Ben Out

Thanks for the assist @nspope!

**Review by nspope — APPROVED** [review]
Beautiful, thanks @benjeffery!!

**Comment by petrelharp** [comment]
Yes! Thanks, both!!!

**Pull request merged**
