### PR TITLE
added the C. elegans genome

### PR DESCRIPTION
**Pull request by attrna**
The genome of C. elegans (issue #834)

I added "mutation_maps.py" that can, potentially, be used as an example for the mutation map feature (#865)

### CODE REVIEW

**Comment by attrna** [comment]
_C. elegans_ has a pretty high selfing rate (99.9%, issue #857),  I multiplied the average recombination rate by its outcrossing rate.

**Comment by jeromekelleher** [comment]
Looks great, thanks @attrna! Would you mind pulling out the genetic and mutation maps and add them separately as follow-up PRs please? This will make it easier to get things merged and also keep track of what's going on.

**Comment by jeromekelleher** [comment]
Great, thanks @attrna! I think it's ready to merge after the commits are squashed. See [here](https://popsim-consortium.github.io/stdpopsim-docs/main/development.html#rebasing) for help.

**Comment by grahamgower** [comment]
Sorry @attrna, it looks like you had this ready to go a week ago and nobody noticed. There have been a bunch of new commits since then. Would you be able to rebase again? Please ping either me or @jeromekelleher afterwards so we make sure you're at the top of the merge queue this time!

**Comment by attrna** [comment]
Hi @grahamgower! I've rebased this PR.

Thanks!

**Comment by grahamgower** [comment]
Thanks @attrna! The final thing to do here is to open a species QC issue using the "Species QC issue template".

**Comment by attrna** [comment]
I apologize for the delay with this.. 

@grahamgower, I have a question about this PR. There's no recombination map here. I tried to PR it with the map but failed (see https://github.com/popsim-consortium/stdpopsim/pull/910). Should I submit the QC for this PR or somehow fix the map first? Do you know if someone could help me with it? I suspect that the issue is somehow related to the map format.


Thank you,
Anastasia

**Comment by grahamgower** [comment]
I think it's fine to open a QC issue now. I'll take a look at your other PR...

**Pull request merged**
