### PR TITLE
DroMel: add assembly ref, and use recomb rates from Comeron map.

### PR DESCRIPTION
**Pull request by grahamgower**
Part of the long-overdue species QC (#541).

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks. 

Any drospophila folks we could ping for a quick once-over on this? Or are you pretty happy this is good to merge @grahamgower?

**Comment by grahamgower** [comment]
> Any drospophila folks we could ping for a quick once-over on this? Or are you pretty happy this is good to merge @grahamgower?

It might be sensible to ping @andrewkern and @jradrion. @jradrion --- I see you did the liftover for the Comeron map at the start of 2019. In light of your recent liftover escapades, is there anything you'd choose to do differently now?

**Comment by jradrion** [comment]
@grahamgower Good question. Let me take a look at this and I'll get back to you.

**Comment by jradrion** [comment]
Hi @grahamgower and @jeromekelleher  

Sorry for the delay; here's a brief summary of where we're at:

I spent considerable time searching for the code I used for the original liftOver of the comeron map from dm3 to dm6. I have come to conclude that I must have run this original liftOver on a now defunct IU compute cluster (where I originally had the UCSC liftOver tool installed), and I must have forgotten to move the script back to our machines at UO before it was automatically purged.

To resolve this I adapted a version of my new maintenance liftOver script specifically for the conversion of the dm3->dm6 map (now found in #574). There are a couple of things that I have changed since the original liftover, most importantly I am using the archived map from FlyBase as our starting point, instead of a converted file I made years ago that only used the midpoints of each interval. Additionally I've added gap-filling that is consistent with how we're filling gaps for the liftover of humans. Long story short, I have a new map for flies that is very similar, but not identical, to the old map. Hopefully we can also archive the code used to generate it in the maintenance directory to avoid this type of problem in the future.

I used the same file pattern as the original, so we should be able to upload the new map to AWS and simulate without issue.

How should I provide the new map? It might be useful if whoever is going to upload it to AWS could try running the code that generates it, just to make sure everything is in working properly?

**Comment by grahamgower** [comment]
Thanks @jradrion! I think having all your maintenance scripts commited is an excellent idea.

PInging @andrewkern and @ndukler, our AWS gatekeepers. Can one of you coordinate to upload the new files?

**Comment by jradrion** [comment]
We will need to upload the revised `DroMel` map files to AWS. @andrewkern or @ndukler, can you help me with this?

**Comment by grahamgower** [comment]
Ping @grahamgower. This needs updating now that #696 has been merged.

**Comment by jeromekelleher** [comment]
Did you mean to ping yourself here @grahamgower?

**Comment by grahamgower** [comment]
> Did you mean to ping yourself here @grahamgower?

Alas, @grahamgower is the one responsible for this, yes.

**Comment by jeromekelleher** [comment]
@grahamgower, what's the status of this PR?

**Comment by grahamgower** [comment]
> @grahamgower, what's the status of this PR?

The basic idea of updating the chromosome-wide recombination rates to use the average from the Comeron recomb map is still valid. But that map was updated recently, so this PR needs to be checked to make sure the average rates calculated here are still correct. And rebase.

**Comment by grahamgower** [comment]
I'm happy that the rates here are fine if you want to take another look @jeromekelleher. I've rebased onto #849.

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Pull request merged**
