### PR TITLE
Release 0.1.1

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by andrewkern** [comment]
hey @jeromekelleher-- hope you had a great holiday... before we push out v0.1.1 are you happy with this https://github.com/popsim-consortium/stdpopsim/issues/359?

**Comment by jeromekelleher** [comment]
Thanks @andrewkern, I had a great holiday, hope you did too!

Yeah #359, looks good @andrewkern --- we're not making any long-term API commitments there, so I'm not worried about the exact form. Good to get the reference assembly in there.

**Comment by andrewkern** [comment]
okay cool just wanted to make sure you saw some of the changes I merged since we were last active. probably time for a call next week?

**Comment by jeromekelleher** [comment]
> okay cool just wanted to make sure you saw some of the changes I merged since we were last active. probably time for a call next week?

Maybe we could leave it another week? I'm at a conference most of next week (hence catching up here first). Call on the 14th?

**Comment by andrewkern** [comment]
that works for me!

**Pull request merged**
