### PR TITLE
PhoSin annotations

### PR DESCRIPTION
**Pull request by chriscrsmith**
So far this includes only the annotations.py file. Waiting on #1514 to add PhoSin to catalog.

@andrewkern, how do we upload files to AWS? Currently the interval files are sitting here:
```
http://sesame.uoregon.edu/~chriscs/StdPopSim/Phocoena_sinus.mPhoSin1.pri.110_exons.tar.gz
http://sesame.uoregon.edu/~chriscs/StdPopSim/Phocoena_sinus.mPhoSin1.pri.110_CDS.tar.gz
```

### CODE REVIEW

**Comment by chriscrsmith** [comment]
Alright I think this is ready to go.

**Comment by nspope** [comment]
i'm going to rerun the test suite, to see if #1532 actually worked (looks like all but one of the grid errored out with "conda environment not found")

**Comment by chriscrsmith** [comment]
Hey @nspope not sure if it's relevant but I'm not passing the stdpopsim pytest until @andrewkern helps me get these files uploaded to AWS

**Comment by nspope** [comment]
that's fine-- just need to get the test suite to run in the first place! Which it seems they aren't, despite #1532

**Comment by nspope** [comment]
@chriscrsmith would you mind rebasing this onto main? I think I've fixed the CI issues, and want to check that the tests actually run now (regardless of whether they fail).

**Comment by chriscrsmith** [comment]
Hows that look, @nspope ? I see some tests running...

**Comment by nspope** [comment]
Seems to be working, thanks!

**Comment by andrewkern** [comment]
@chriscrsmith I think the correct way to do this is to actually to merge this PR and then run the annotation maintenance and it will automatically do the downloading etc. 

anyone mind if I do that?

**Comment by andrewkern** [comment]
the annotations are now up on aws

**Pull request merged**
