### PR TITLE
Warn when the user runs simulations of non-autosomes.

### LINKED ISSUE #384: Warn when user runs simulations of x chromosome
When the user runs a simulation of the X chromosome, we should emit a warning. Probably the best thing to do is to have an ``autosome`` boolean attribute we associate with each chromosome in the genome definitions, and then we ``warnings.warn()`` when a simulation is attempted where ``autosome`` is False.

This should be done reasonably quickly and be pushed into a release so we are not misleading users about the quality of our non-autosomal simulations.

See #383 for background.

### PR DESCRIPTION
**Pull request by grahamgower**
Currently affects:
CanFam chrX
DroMel chrX chrY chrM
PonPyg chrX
HomSap chrX chrY

Closes #384.

### CODE REVIEW

**Comment by grahamgower** [comment]
I didn't add a boolean field for each chromosome entry like suggested in #384. Given that this "fix" is going to be yanked out anyway, and we only have chromosomes with well defined names, this seemed far less invasive.

**Comment by jeromekelleher** [comment]
Fair enough -- this works! One thing though, shouldn't we also worry about people using the Python API?

**Comment by grahamgower** [comment]
Yep, good point. I moved the chomosome name check into Species.get_contig().

**Comment by jeromekelleher** [comment]
Nice, good pragmatic fix. Merging.

**Pull request merged**
