### PR TITLE
Add Canis familiaris to species catalog.

### PR DESCRIPTION
**Pull request by grahamgower**
TODO: species specific tests and rtd stuff. Anything else missing?

### CODE REVIEW

**Comment by andrewkern** [comment]
looks good. just missing the RTD stuff and tests, yeah

**Comment by andrewkern** [comment]
was the RTD thing with the citations to blame here for the ci error?

**Comment by grahamgower** [comment]
Yep. And as far as I can tell, the unit tests that are missing from this PR would only be like those I'm complaining about in #376.

**Comment by andrewkern** [comment]
just looked at that issue. for now lets stick to including too many unit tests i think and if you agree we can get this one merged

**Comment by grahamgower** [comment]
Ok, I added the unit test file. In the spirit of providing solutions, and not just criticism, I put in an end-to-end test (i.e. test that this runs: `stdpopsim CanFam -c chr38 -l 0.001 --seed 1234 -q 10`).

**Comment by jeromekelleher** [comment]
This is excellent, thanks @grahamgower! It would be nice to add tests for pop size as I discussed in #376, but otherwise LGTM.

**Comment by jeromekelleher** [comment]
I'm happy to merge here. I'll let @andrewkern push the button in case there's anything he spots.

**Comment by andrewkern** [comment]
looks really good. i like the end-to-end test especially @grahamgower. this might be a good standard to adopt for each species.

**Pull request merged**
