### PR TITLE
QC for HolsteinFriesian_1M13 demographic model for BosTau

### PR DESCRIPTION
**Pull request by igronau**
[  including updated mutation rate in doc for BosTau demographic model
  (HolsteinFriesian_1M13.csv) to fit the one used in model   ]

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@igronau This makes perfect sense to me! Thanks!

**Comment by petrelharp** [comment]
Great! Is this ready to merge then, @igronau?

**Comment by igronau** [comment]
Yes.

**Review by grahamgower — APPROVED** [review]
LGTM. Thanks @igronau.

**Pull request merged**
