### PR TITLE
Illustrate use of both dtwf and hudson msprime models

### PR DESCRIPTION
**Pull request by hyanwong**
I always forget what the syntax is here! I think others might find it useful.

### CODE REVIEW

**Comment by petrelharp** [comment]
I like the idea, but sticking this in the "quickstart" doesn't seem like the right place for it? Perhaps under a new subheader "Advanced: switching demographic models"?

**Comment by hyanwong** [comment]
This addition isn't in the first introduction to stdpopsim example code (which is under the heading "Running a published model"). Rather it is in the (more advanced) "Running a generic model" section which follows that. So I reckon it's not really treated as a "Quickstart" example IMO, and is probably fine where it is?

**Comment by petrelharp** [comment]
It's still fairly "quickstart"-ish; what about in the new section ("tips and tricks and gotchas") I'm proposing adding in #1601?

**Comment by petrelharp** [comment]
I changed my mind here - this is good practice, and as you say this isn't the very first demonstration. But, I've rewritten it a bit and added a link to the DTWF paper - what do you think?

**Comment by hyanwong** [comment]
Yes, this LGTM. Merge away!

**Pull request merged**
