### PR TITLE
Add final changes

### PR DESCRIPTION
**Pull request by ornobalam**
Attempting after installing pre-commit hooks

### CODE REVIEW

**Comment by nspope** [comment]
Superceded by #1482

**Comment by ornobalam** [comment]
Hi! Apologies for this, but I just noticed that the parameter table update did not go through (it still reads 3.2e-9). Please let me know what I should do.

**Comment by nspope** [comment]
No worries, I can fix -- so to match the implementation, the mutation rate in the table should be 9.0333e-9 ?

**Comment by ornobalam** [comment]
Yes! Thanks for taking care of it

**Pull request closed without merging**
