### PR TITLE
Add Streptococcus agalactiae CC17 strains. 

### PR DESCRIPTION
**Pull request by jeanrjc**
Follow up PR for issue #843.

I discussed in the corresponding issue how I came up with the parametrization.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Sorry, this the wrong button!

**Comment by jeromekelleher** [comment]
Looks great to me @jeanrjc! A couple of minor things:

- Looks like your github email isn't in sync (so you won't get contributations attributed to you correctly). See [here](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#:~:text=Your%20local%20Git%20commit%20email%20isn't%20connected%20to%20your%20account&text=The%20email%20address%20in%20the,the%20local%20git%20config%20settings.&text=If%20you%20use%20such%20an,up%20in%20your%20contributions%20graph.) for more info
- Once you've sorted this out, can you squash the commits down please? (https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing)

thanks for the contribution!

**Comment by jeanrjc** [comment]
> Looks like your github email isn't in sync (so you won't get contributations attributed to you correctly). See [here](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#:~:text=Your%20local%20Git%20commit%20email%20isn't%20connected%20to%20your%20account&text=The%20email%20address%20in%20the,the%20local%20git%20config%20settings.&text=If%20you%20use%20such%20an,up%20in%20your%20contributions%20graph.) for more info

ah damned, it's an old email address that was hanging around in an old global .gitconfig. Do you know if I can change it in the commit ? Maybe while rebasing ?

**Comment by jeromekelleher** [comment]
> ah damned, it's an old email address that was hanging around in an old global .gitconfig. Do you know if I can change it in the commit ? Maybe while rebasing ?

You can change it with commit --amend I think, or by "edit"ing during the rebase.

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Pull request merged**
