### PR TITLE
Build SLiM in Circle CI and Travis CI environments.

### LINKED ISSUE #255: [slim-engine-dev] build SLiM on CircleCI
E.g. something like https://github.com/tskit-dev/msprime/blob/master/data/Makefile#L3

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #255.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I think I'd prefer to just keep it all in the CI script and get rid of the makefile @grahamgower --- I don't want to get involved in compiling SLiM for users, that gets very messy.

**Comment by grahamgower** [comment]
Ok, I can do that. Any pointers for the travis CI build? I couldn't find anything equivalent to circle's `circleci local execute`.

**Comment by grahamgower** [comment]
Looks like some networking issues on the CI server(s). I'm going to stop pushing more of these: I think the changes are working as intended.

**Comment by jeromekelleher** [comment]
Recipe LGTM @grahamgower. Can you try again with the Circle build please?

**Pull request merged**
