### PR TITLE
Fix Tennessen two-pop migration rates in QC implementation

### PR DESCRIPTION
**Pull request by apragsdale**
Along with #520

### CODE REVIEW

**Comment by ndukler** [comment]
Looks like we both saw the same thing. @jeromekelleher can you pull in #520  then #521? Or do we have to do it simultaineously to prevent the tests from failing?

**Comment by petrelharp** [comment]
Hm, it would be nice to get checks passing before merging; do you think that if these changes are made on top of #520 then checks will pass? If so, the right thing to do is probably to put this commit over at #520 also?

**Comment by ndukler** [comment]
Ok, @apragsdale can you make this PR to my repo then I guess? Then I can merge it into my branch?

**Comment by apragsdale** [comment]
Ok, I'll do that and close this PR

**Comment by petrelharp** [comment]
Hm, I think that @ndukler meant for you to change the "base" branch of this PR to his branch, so that if he clicks "merge" it'd go into his. But, @ndukler - if `origin` is the popsim-consortium repo, and you're on your `mass_migration_bugfix` branch you can do something like:
```
git fetch origin pull/521/head:pr521
git cherry-pick pr521
```
and you should have @apragsdale's commit on top of your branch?

**Comment by apragsdale** [comment]
Oh, I didn't realize I could do that. I re-opened a new PR to his branch instead, which should do the same thing?

**Pull request closed without merging**
