### PR TITLE
Add virtual env for Python dependencies

### LINKED ISSUE #615: add maintenance folder to `flake8` lines in continuous integration checks
I think this needs to go in `.circleci/config.yml`. It looks like there are a couple of minor lint things that need fixing in the maintenance folder to go along with this change.

### PR DESCRIPTION
**Pull request by platipo**
Fixes #615

### CODE REVIEW

**Comment by platipo** [comment]
@grahamgower I need you to activate the orbs feature via CircleCI because `To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.`

**Comment by grahamgower** [comment]
> @grahamgower I need you to activate the orbs feature via CircleCI because `To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.`


Hi @platipo. I don't have admin access for the circle ci account, and Jerome is on leave right now (he almost certainly set this up originally). Can we do without using orbs for now? Or maybe @andrewkern or @petrelharp (or even @benjeffery?) also have the circleci keys for the `popsim-consortium` organization?

**Comment by benjeffery** [comment]
I just checked and I don't, sorry!

**Comment by petrelharp** [comment]
Turns out I do! I think I've enabled orbs?

**Comment by platipo** [comment]
Yeah! Thank you @petrelharp, now orbs are enabled!

**Comment by platipo** [comment]
The whole refactoring of the CircleCI configuration is done!

This is the new workflow:

workflow

The new jobs are:
- **lint**: runs the linting on the code (the `maintenance` directory is been added). I took the liberty not to add this job to any requirement bu it your opinion that matters.
- **build-slim-lib**: build and caches from the SLiM Github repo the last known tag.
- **build-pkg**: Build and caches the building of the stdpopsim package.
- **docs**:  Make the documentation.
- **test**: Run the all tests in parallel between multiple containers; now you can access and see failing tests going to [the test tab in the tes job of the workflow](https://app.circleci.com/pipelines/github/popsim-consortium/stdpopsim/1358/workflows/f62bd195-d094-40cd-973a-a67ba31837e7/jobs/1477/parallel-runs/0?filterBy=ALL).

The graph describes the requirements for the various job and the jobs that can run in parallel.

The mean reduction in build time is 50%, overall this workflow is faster than the previous one.

**Comment by platipo** [comment]
Of course the checks are failing because the linting step is raising:
```
maintenance/ensembl.py:74:36: F541 f-string is missing placeholders
maintenance/__init__.py:4:1: F403 'from .ensembl import *' used; unable to detect undefined names
maintenance/__init__.py:4:1: F401 '.ensembl.*' imported but unused
```

**Comment by platipo** [comment]
Finally there are a couple of improvements that can be done:
- As you can see almost every step re installs the `libgsl-dev` library so much so that I created the alias `install_libgsl`; the improvement could be to write and publish a Docker image that caches that library. (Minor improvement)
- I really struggled with the Python requirements because I use them as the key for the CicleCI caches. The current usage of  the `requirements/development.txt` can cause misalignment bettwen the CI packages and local packages because the packages are not pinned. Also the requirements contains many packages required by only one workflow steps like `sphinx` for the documentation or `flake8` for the linting job. Maybe a more structured tool to pin the requirements and obtain a deterministic build is required (one proposal may be `pip-tools`). 

Let me know what you think @grahamgower, @petrelharp and @benjeffery !

**Comment by grahamgower** [comment]
Wow! This is a fantastic improvement, thanks @platipo!

**Comment by platipo** [comment]
Thanks @grahamgower, I'm partecipating to the [Orbtoberfest](https://hacktoberfest.circleci.com/) sponsored by CircleCI, can you add the label `Orbtoberfest`? This allows CicleCI to count my contributions.

**Pull request merged**
