### PR TITLE
Updating to work with msprime 1.0 beta

### LINKED ISSUE #837: Some breaking changes in `msprime` 1.0 beta
`msprime.RateMap` now only takes keyword arguments, but we use positional arguments (as in `msprime.RateMap(positions, rates)`) in the tests.

That's an easy fix, but there may be some other breaking changes that haven't been noticed yet.

### PR DESCRIPTION
**Pull request by apragsdale**
Fixes #837

I'm assuming that the msprime 1.0 release will not have drastic changes to the API from the beta version, so can get to work fixing some of the changes in msprime that no longer work here.

### CODE REVIEW

**Comment by apragsdale** [comment]
I don't think these tests should be passing. Does it cache older versions of msprime?

**Comment by jeromekelleher** [comment]
Ugh - so, what we're being hit by here is the fact we don't have a conda package for the beta. Probably the easiest thing to do for now is to post install the beta from pip after the conda commands have completed. It's too painful trying to get a proper pre-release on conda-forge, I'm afraid.

**Comment by jeromekelleher** [comment]
I'll tack on some commits to get this working @apragsdale - we need to get it sorted soon and I'm more up to speed with the quirks.

**Comment by apragsdale** [comment]
Want to me to close this and let you handle it @jeromekelleher? I started this PR before realizing there are some issues I wasn't sure exactly how to handle best.

**Comment by jeromekelleher** [comment]
I'll keep working here, thanks @apragsdale, leave it with me.

**Comment by jeromekelleher** [comment]
Hopefully that'll sort it. @grahamgower, I had to do a bit of work on the model spec for the CLI, hopefully nothing is changed too much. Also saw some weirdness in the test_slim_engine stuff, that'll need a look at some point. 

Looks like there's a lot of updating to do to be done... will have to start looking and making a roadmap for the next version once msprime 1.0 is tagged.

**Review by grahamgower — APPROVED** [review]
LGTM. If you open an issue for the failing SLiM test I can take a look during the hackathon.

**Pull request merged**
