### PR TITLE
require msprime-1.0

### PR DESCRIPTION
**Pull request by grahamgower**
This PR is against a new `msprime-1.0` feature branch. In this branch, we can use features of the as-yet-unreleased msprime-1.0. E.g. #644.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Uggh, that manual build is not going to be easy on windows. Could skip windows tests entirely on this branch?

**Comment by grahamgower** [comment]
Actually the last push seems to work ok on windows. Now there's a failing slim engine test though.
```
ERROR: test_recap_and_rescale (tests.test_slim_engine.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/stdpopsim/stdpopsim/tests/test_slim_engine.py", line 161, in test_recap_and_rescale
    ts1 = engine.simulate(
  File "/home/runner/work/stdpopsim/stdpopsim/stdpopsim/slim_engine.py", line 1123, in simulate
    ts = self._recap_and_rescale(
  File "/home/runner/work/stdpopsim/stdpopsim/stdpopsim/slim_engine.py", line 1248, in _recap_and_rescale
    msprime.mutate(
  File "/usr/share/miniconda/envs/stdpopsim/lib/python3.9/site-packages/msprime/mutations.py", line 1191, in mutate
    _msprime.sim_mutations(
_msprime.LibraryError: Kept mutations must have known mutation times.
```
Technically, this is a regression, as it is accepted with msprime 0.7.4. Murrillo has done this to make it work in #644: https://github.com/popsim-consortium/stdpopsim/pull/644/files#diff-971e0c3ab37a1dafcaa06c7ff25e52b2fd5803b10a2f1cec3a469bcd903c7e7dR1204-R1212
 Thoughts @jeromekelleher?

**Comment by jeromekelleher** [comment]
That sounds tricky @grahamgower - could we skip this test for the moment and file an issue to track? It might need some upstream changes to sort out, if it is a regression.

**Comment by grahamgower** [comment]
I'm going to merge this in to the feature branch without fixing the slim code. @mufernando has the appropriate fix in his PR, and it would be nice for that PR to be retargetted onto this branch.

**Pull request merged**
