### PR TITLE
Change SLiM engine parameters and default behaviour.

### LINKED ISSUE #420: Decide how we should handle `burn in` in the SLiM engine
The SLiM engine currently supports using recapitation, or not. When recapitation is disabled, we wait until all individuals have a common ancestor after the start of the simulation, and then we wait an additional `10*N` generations. N is taken to be the maximum population size of the populations that exist at the start of the simulation (all current models only have one). We currently have separate CLI options to disable recaptitation (`--slim-no-recapitation`) and to disable burn in (`--slim-no-burnin`).

In reviewing #409, @andrewkern suggested that the burn in time should be configurable, at least from the python API; and that we probably don't need both CLI options.

I propose that:
1. We change the `--slim-no-burnin` parameter to be `--slim-burnin X`, where `X` specifies the length of the burn in period, in units of N generations. This can be set to zero to disable burn in.
2. We add an option to disable checking for coalescence, separately to the burn in. This might be desirable in the future for non-neutral simulations that use a distribution of fitness effects (DFE). In such cases, we probably want to: disable checking for coalescence (because it will be really slow), specify a fixed burn in time with the DFE, and then optionally do recapitation to fix up genealogies without a single root.

We don't have to do (2) now. Another option is to get rid of checking for coalescence entirely.

### PR DESCRIPTION
**Pull request by grahamgower**
* Always do recapitation.
 * --slim-scaling-factor defaults to 1.
 * --slim-burn-in defaults to 10*N generations.

Closes #420, #445, and #449.

### CODE REVIEW

**Comment by grahamgower** [comment]
validation.py will also need updating, but I'll tackle that separately.

**Comment by grahamgower** [comment]
All the tests pass for me locally. Maybe this is a version specific failure, for some dependency (e.g. circleci runs python 3.6, I'm running 3.8).

@jeromekelleher Are you able to poke circleci to build git master again? I really want to know if something has changed since the last pr was merged.

**Comment by grahamgower** [comment]
Nevermind about poking circleci. The dependency whose version changed is pyslim. I can reproduce this error of too many roots after updating to `pyslim 0.400`

CC @petrelharp

**Comment by petrelharp** [comment]
Ok, I've done this and updated things on pip. Using whatever version of msprime plus pyslim 0.401 should work now.

**Comment by petrelharp** [comment]
Looks good to me! Thanks a bunch!!

**Pull request merged**
