### PR TITLE
Add warning in SLiM engine for odd sample sizes.

### LINKED ISSUE #464: different number of samples from slim and msprime engines
SLiM simulates diploid individuals, so for a requested sample size `n`, this corresponds to `n/2` individuals; except when `n` is odd, `(n+1)/2` individuals are simulated instead because we can't simulate half an individual. Msprime simulates haploids, which don't explicitly correspond to individuals, so you get `n` haploids. See the examples below. I think this behaviour is correct, but possibly unexpected for odd values of `n`. Perhaps we should warn the user in this case?

SLiM:
```
$ stdpopsim -e slim --slim-scaling-factor 10 HomSap -c chr22 -l 0.05 -o slim.ts -d OutOfAfrica_2T12 2 3
Simulation information:
    Engine: slim (3.3.2)
    Model id: OutOfAfrica_2T12
    Model desciption: Two population out-of-Africa
    Population: number_samples (sampling_time_generations):
        AFR: 2 (0)
        EUR: 3 (0)
Contig Description:
    Contig length: 2565228.3000000003
    Mean recombination rate: 1.4445022767788226e-08
    Mean mutation rate: 1.29e-08
    Genetic map: None

If you use this simulation in published work, please cite:
[simulation engine]
  Haller et al., 2019: https://doi.org/10.1111/1755-0998.12968
[genome assembly]
  The Genome Sequencing Consortium, 2001: http://dx.doi.org/10.1038/35057062
[mutation rate]
  Tian, Browning, and Browning, 2019: https://doi.org/10.1016/j.ajhg.2019.09.012
[recombination rate]
  The International HapMap Consortium, 2007: https://doi.org/10.1038/nature06258
[demographic model]
  Tennessen et al., 2012: https://doi.org/10.1126/science.1219240
[demographic model]
  Fu et al., 2013: https://doi.org/10.1038/nature11690
```
```
$ tskit info slim.ts
sequence_length:  2565228.0
trees:            2115
samples:          6
individuals:      3
nodes:            1426
edges:            6193
sites:            2450
mutations:        2450
migrations:       0
populations:      2
provenances:      5
```

Msprime:
```
$ stdpopsim HomSap -c chr22 -l 0.05 -o msprime.ts -d OutOfAfrica_2T12 2 3
Simulation information:
    Engine: msprime (0.7.4)
    Model id: OutOfAfrica_2T12
    Model desciption: Two population out-of-Africa
    Population: number_samples (sampling_time_generations):
        AFR: 2 (0)
        EUR: 3 (0)
Contig Description:
    Contig length: 2565228.3000000003
    Mean recombination rate: 1.4445022767788226e-08
    Mean mutation rate: 1.29e-08
    Genetic map: None

If you use this simulation in published work, please cite:
[simulation engine]
  Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
  The Genome Sequencing Consortium, 2001: http://dx.doi.org/10.1038/35057062
[mutation rate]
  Tian, Browning, and Browning, 2019: https://doi.org/10.1016/j.ajhg.2019.09.012
[recombination rate]
  The International HapMap Consortium, 2007: https://doi.org/10.1038/nature06258
[demographic model]
  Tennessen et al., 2012: https://doi.org/10.1126/science.1219240
[demographic model]
  Fu et al., 2013: https://doi.org/10.1038/nature11690
```
```
$ tskit info msprime.ts
sequence_length:  2565228.3000000003
trees:            1871
samples:          5
individuals:      0
nodes:            1290
edges:            5391
sites:            2417
mutations:        2417
migrations:       0
populations:      2
provenances:      2
```

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #464.

### CODE REVIEW

**Comment by grahamgower** [comment]
I've used `warnings.warn` here. But I think this produces really ugly output.
```
$ stdpopsim -e slim --slim-script HomSap -d OutOfAfrica_2T12 3 5 -q > /dev/null
/home/grg/src/stdpopsim/stdpopsim/slim_engine.py:523: UserWarning: SLiM simulates diploid individuals, so 2 individuals will be sampled for the 3 haploids requested from population AFR at time 0.0. See #464.
  warnings.warn(
/home/grg/src/stdpopsim/stdpopsim/slim_engine.py:523: UserWarning: SLiM simulates diploid individuals, so 3 individuals will be sampled for the 5 haploids requested from population EUR at time 0.0. See #464.
  warnings.warn(
```

**Comment by jeromekelleher** [comment]
We could use logger.warn() here, which would be much better for the CLI. BUT this means that warnings would end up being silent for a lot of API users, unless they set up logging output (which they won't).

But, we could use [captureWarnings](https://docs.python.org/3/library/logging.html#logging.captureWarnings) handle the output within a standard CLI output infrastructure (as discussed in #473).

So, the PR looks good, and we just need to manage the CLI output better?

**Comment by grahamgower** [comment]
Yep, thanks. I'm happy with this PR as is, and will take care of the warning format elsewhere.

**Comment by jeromekelleher** [comment]
Great, merging then.

**Pull request merged**
