### PR TITLE
Rounded mutation & recomb rate to the 4th dec

### PR DESCRIPTION
**Pull request by ragreenburg**

### CODE REVIEW

**Comment by grahamgower** [comment]
Hi @ragreenburg. I think it would be better to keep the precision of the parameters themselves, but just change how many digits are being printed in the `get_species_help()` function. https://github.com/popsim-consortium/stdpopsim/blob/403e350ec71e57e8c13355ea516f25cc2a4684bb/stdpopsim/cli.py#L182-L194

**Comment by ragreenburg** [comment]
> 
> 
> Hi @ragreenburg. I think it would be better to keep the precision of the parameters themselves, but just change how many digits are being printed in the `get_species_help()` function.
> 
> https://github.com/popsim-consortium/stdpopsim/blob/403e350ec71e57e8c13355ea516f25cc2a4684bb/stdpopsim/cli.py#L182-L194

Okay, I will fix that!

**Comment by grahamgower** [comment]
It might be simpler to use python's [format specifier](https://docs.python.org/3.4/library/string.html#format-string-syntax) here. I didn't see a simple example in the python docs, but I was thinking it would look something like `f"Mutation rate: {species.genome.mean_mutation_rate:.4g}\n"` (use scientific notation (`g`) with 4 digits after the decimal place `.4`).

**Comment by grahamgower** [comment]
Perfect! Thanks @ragreenburg! Sorry for the run-around :-) One last thing, and I think it'll be ready to merge. Could you "squash" all your changes down to one commit? (See https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing)

I'm off to bed now, but I'll take another look first thing in the morning.

**Comment by ragreenburg** [comment]
@grahamgower Sure, I can do that. Absolutely no problem haha. Have a good night!

**Comment by grahamgower** [comment]
Looks good @ragreenburg. Merging now.

**Pull request merged**
