### PR TITLE
Fix unit testing to work with msprime > 0.7.4.

### LINKED ISSUE #518: Tests no longer pass with msprime update
There was a recent change (this week) to msprime dev branch that removes an argument to `get_ll_representation` (this commit: https://github.com/tskit-dev/msprime/commit/cd522e3361d21a93d7ed6c8323a8dbb065630481#diff-3af8c5bda4976d0bd25e9e5754497a74). This now breaks the tests, so that all model equivalency tests fail with `TypeError: get_ll_representation() takes 1 positional argument but 2 were given` if you have the up to date msprime dev branch installed.

This is a pretty straightforward fix, but I guess this highlights the overall fragility of the stdpopsim resource as a whole which relies on other software that is also continuously developed. If a simulation backend changes, which they are bound to do, that could leave us with a stdpopsim that cannot run some of the unit tests, like here, or doesn't work at all. Or that it works with one release of msprime, but not a later one.

Is this an issue that has been generally discussed, with steps we take to make sure that stdpopsim still works as backends are updated and changed?

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #518.

### CODE REVIEW

**Comment by grahamgower** [comment]
There's something wrong with the codecov report. This should definitely have failed, as I added a code path without a test for it.

**Comment by grahamgower** [comment]
I added a test for the version compatibility shim, and checked it under both msprime 0.7.4, and git master.

```
$ python -c "import msprime; print(msprime.__version__)"
0.7.4
$ rm .coverage
$ nosetests --with-coverage --cover-package stdpopsim tests
...............................................................................................................................................................................................................................................................................................................................................S
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
stdpopsim/__init__.py                             21      2    90%
stdpopsim/_version.py                              1      0   100%
stdpopsim/cache.py                                16      0   100%
stdpopsim/catalog/__init__.py                      0      0   100%
stdpopsim/catalog/arabidopsis_thaliana.py         41      0   100%
stdpopsim/catalog/canis_familiaris.py             15      0   100%
stdpopsim/catalog/drosophila_melanogaster.py      52      0   100%
stdpopsim/catalog/e_coli.py                        8      0   100%
stdpopsim/catalog/homo_sapiens.py                332      0   100%
stdpopsim/catalog/pongo_abelii.py                 40      0   100%
stdpopsim/citations.py                            48      0   100%
stdpopsim/cli.py                                 302      2    99%
stdpopsim/engines.py                              56      0   100%
stdpopsim/genetic_maps.py                         83      1    99%
stdpopsim/genomes.py                              55      0   100%
stdpopsim/models.py                              190      0   100%
stdpopsim/qc/__init__.py                           4      0   100%
stdpopsim/qc/arabidopsis_thaliana_qc.py           42      0   100%
stdpopsim/qc/drosophlia_melanogaster_qc.py        36      0   100%
stdpopsim/qc/homo_sapiens_qc.py                  258      0   100%
stdpopsim/qc/pongo_abelii_qc.py                   25      0   100%
stdpopsim/slim_engine.py                         223      0   100%
stdpopsim/species.py                              73      0   100%
stdpopsim/utils.py                                16      0   100%
------------------------------------------------------------------
TOTAL                                           1937      5    99%
----------------------------------------------------------------------
Ran 336 tests in 44.248s

OK (SKIP=1)

```

```
$ python -c "import msprime; print(msprime.__version__)"
0.7.5.dev215+ng2ccf262
$ rm .coverage
$ nosetests --with-coverage --cover-package stdpopsim tests
...............................................................................................................................................................................................................................................................................................................................................S
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
stdpopsim/__init__.py                             21      2    90%
stdpopsim/_version.py                              1      0   100%
stdpopsim/cache.py                                16      0   100%
stdpopsim/catalog/__init__.py                      0      0   100%
stdpopsim/catalog/arabidopsis_thaliana.py         41      0   100%
stdpopsim/catalog/canis_familiaris.py             15      0   100%
stdpopsim/catalog/drosophila_melanogaster.py      52      0   100%
stdpopsim/catalog/e_coli.py                        8      0   100%
stdpopsim/catalog/homo_sapiens.py                332      0   100%
stdpopsim/catalog/pongo_abelii.py                 40      0   100%
stdpopsim/citations.py                            48      0   100%
stdpopsim/cli.py                                 302      2    99%
stdpopsim/engines.py                              56      0   100%
stdpopsim/genetic_maps.py                         83      1    99%
stdpopsim/genomes.py                              55      0   100%
stdpopsim/models.py                              190      0   100%
stdpopsim/qc/__init__.py                           4      0   100%
stdpopsim/qc/arabidopsis_thaliana_qc.py           42      0   100%
stdpopsim/qc/drosophlia_melanogaster_qc.py        36      0   100%
stdpopsim/qc/homo_sapiens_qc.py                  258      0   100%
stdpopsim/qc/pongo_abelii_qc.py                   25      0   100%
stdpopsim/slim_engine.py                         223      0   100%
stdpopsim/species.py                              73      0   100%
stdpopsim/utils.py                                16      0   100%
------------------------------------------------------------------
TOTAL                                           1937      5    99%
----------------------------------------------------------------------
Ran 336 tests in 44.207s

OK (SKIP=1)
```

**Comment by jeromekelleher** [comment]
Nicely done @grahamgower, thanks. Another option would be to back out of the change in msprime where we dropped the unused argument. It's no harm, and we could mark it for removal some time in the future after msprime 1.0 and we've transitioned stdpopsim to using ``asdict()`` like you say.

Otherwise, we'll still have the problem that people with older versions of stdpopsim will break when msprime 1.0 is released.

**Comment by jeromekelleher** [comment]
I don't mind breaking test code, but we can't break production code. So, backing out of msprime change seems simplest?

**Comment by grahamgower** [comment]
Sure, that's fine too. Note also that the behaviour of `msprime.SimpleBottleneck` changed: it previously had a default for the `population` attribute, but this seems to have been removed.

**Comment by jeromekelleher** [comment]
Reverted the change to msprime in tskit-dev/msprime#1038

See tskit-dev/msprime#1036 and tskit-dev/msprime#1037 for longer term plan.

**Comment by jeromekelleher** [comment]
> Sure, that's fine too. Note also that the behaviour of msprime.SimpleBottleneck changed: it previously had a default for the population attribute, but this seems to have been removed.

Is the SimpleBottleneck used here somewhere? (It was never documented, so I felt OK to change it). Can you open an issue on msprime to track the problem if so, please?

**Pull request closed without merging**
