### PR TITLE
Use 3375 generations for Nea/Nea split time in PapuansOutOfAfrica_10J19.

### PR DESCRIPTION
**Pull request by grahamgower**
Found by @noscode during QC, #373.

### CODE REVIEW

**Comment by ndukler** [comment]
@grahamgower Make sure you propagate any changes in parameter values to the documentation, in particular the parameter table.

**Comment by grahamgower** [comment]
Ah, yes. Thanks @ndukler

**Comment by jeromekelleher** [comment]
LGTM, happy to merge this if I get thumbs up from @ndukler.

**Comment by ndukler** [comment]
This looks mostly good. Just should probably have some indication in the table of what the generation time used to translate between the years on the parameter table and the generations in the model is. I know there is a default but I think it is better to be explicit.

**Comment by noscode** [comment]
I found another thing that looks like a mixed up populations. It is in the same issue. So may be @grahamgower will check and add it here too?

**Comment by grahamgower** [comment]
@ndukler I moved the generation time to the top of the parameter table, where it should be more obvious.

@noscode Thanks for tracking down the mixed up popuations. I've fixed that too.

**Comment by noscode** [comment]
That's great @grahamgower! You are welcome. I will make QC PR after this will be merged.

**Comment by jeromekelleher** [comment]
OK, I'm going to merge this to @noscode's PR can be updated. @ndukler, please shout out if there was anything else needed here so we can follow up.

**Pull request merged**
