### PR TITLE
more issue templates

### PR DESCRIPTION
**Pull request by petrelharp**
Right now the "new issue" page makes it look like the only way to submit an issue is as a QC issue; this will fix that (and give a bit more guidance).
Screenshot from 2020-05-01 08-58-24

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM. Can we get the "Bug" label to automatically populate for the "Bug Report" type @agladstein?

**Comment by petrelharp** [comment]
I think we can, but I thought we should let a developer decide if it's actually a bug.

**Comment by agladstein** [comment]
Yes, we can automatically label it as bug. But, I think @petrelharp is right that a developer could add that label.

Looks good to me.

**Comment by grahamgower** [comment]
Looks good to me too! I tend to agree that a developer should decide if a report is an actual bug. But the "feature request" template could certainly use the `enhancement` tag.

**Comment by petrelharp** [comment]
Ok, I've  added the `enhancement` tag, and sounds like I can merge this - hopefully it works as we expect... the github docs are not exhaustive.

**Comment by petrelharp** [comment]
Seems to work!
Screenshot from 2020-05-02 12-01-22

**Pull request merged**
