### PR TITLE
Remove Circle CI.

### LINKED ISSUE #779: upload coverage report in GitHub Actions workflow, and remove Circle CI action
It's fairly time consuming to learn/understand any one CI system, so to have both Circle and GitHub Actions (GHA) is quite a maintenance burden. I think GHA is simpler though? (Although GHA is still annoyingly complicated). I admit, I haven't tried to grok Circle, so have a bias towards GHA. If we do the codecov upload with GHA, then we can remove Circle. To remove GHA, we'd have to add a bunch of new OS/Python platform combinations to Circle.

### LINKED ISSUE #1222: CI tests should run in verbose mode
This would make it much easier to track down problems like the OOM issue seen in #1216.

### PR DESCRIPTION
**Pull request by grahamgower**
This moves codecov reporting into github actions.

Closes #779.
Closes #1222.

### CODE REVIEW

**Comment by grahamgower** [comment]
I've disabled the circle CI webhook in the [github settings panel](https://github.com/popsim-consortium/stdpopsim/settings/hooks), but I didn't delete the webhook. I also didn't delete the deploy key. So we can easily reenable circle if we have to.

Codecov for this PR was evidently uploaded successfully (https://codecov.io/gh/popsim-consortium/stdpopsim/commit/19713134fd5b1deeef7807414a675bab3ec3144c/), so I'm not sure why codecov didn't comment here with a coverage report as usual.

**Comment by petrelharp** [comment]
Hm - we do want the codecov comments; perhaps it won't comment until it's merged in to `main`?

**Comment by grahamgower** [comment]
Yes, I think that it will work once this is merged. We're now reporting coverage info for 6 OS/PYTHON combinations (as opposed to one before), so probably there wont be any base commit against which this new info can be compared - until this is merged.

**Comment by petrelharp** [comment]
Well, looks good to me - go ahead and merge?

**Pull request merged**
