### PR TITLE
Convert sampling time to years, like other times.

### PR DESCRIPTION
**Pull request by grahamgower**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I thought times were all generations by default? (see #75?)

**Comment by grahamgower** [comment]
All times written in the slim script are in years.

**Comment by grahamgower** [comment]
Let me clarify. The slim script generated by the slim engine has all times specified in years, includes the generation_time variable, and when slim executes the script times are explicitly converted to generations. The output tree sequence is in units of generations, and is not impacted by this.

**Comment by jeromekelleher** [comment]
OK, sounds good. Any way we can unit test this so that we don't get regressions?

**Comment by grahamgower** [comment]
I'm open to suggestions, but can't think how this is could be done without parsing the slim script or the debug statments the script prints when slim runs.

**Comment by jeromekelleher** [comment]
Yeah, looks tricky. I'm happy to merge - should we merge or wait for input from others?

**Comment by grahamgower** [comment]
Merge, merge, merge! :P

It fixes validation of AncientEurasia_9K19 btw.

**Comment by jeromekelleher** [comment]
Done!

**Pull request merged**
