### PR TITLE
Set population names in SLiM code.

### LINKED ISSUE #1140: recapitation fails with new SLiM because of mismatching population names
Using the development version of SLiM, running the example from the `analysis2/README.md`:
```
import numpy as np
import stdpopsim

species = stdpopsim.get_species("HomSap")

# Adding a specific Distribution of fitness effects
dfe = species.get_dfe("Gamma_K17")

contig = species.get_contig("chr20")
model = species.get_demographic_model("OutOfAfrica_3G09")
samples = model.get_samples(100, 100, 100)  # YRI, CEU, CHB

# Extracting gene annottation
exons = species.get_annotations("ensembl_havana_104_exons")
exon_intervals = exons.get_chromosome_annotations("chr20").astype("int")
contig.add_dfe(intervals=exon_intervals, DFE=dfe)

# Engine used for simulations
engine = stdpopsim.get_engine("slim")

# Simulate
ts = engine.simulate(
    model,
    contig,
    samples,
    seed=236,
    slim_scaling_factor=100,
    slim_burn_in=10,
)
```

... gets the following error:
```
Traceback (most recent call last):
  File "/home/peter/projects/popsim-consortium/analysis2/test.py", line 22, in <module>
    ts = engine.simulate(
  File "/home/peter/.local/lib/python3.9/site-packages/stdpopsim-0.1.3b1-py3.9.egg/stdpopsim/slim_engine.py", line 1281, in simulate
    ts = self._recap_and_rescale(
  File "/home/peter/.local/lib/python3.9/site-packages/stdpopsim-0.1.3b1-py3.9.egg/stdpopsim/slim_engine.py", line 1394, in _recap_and_rescale
    ts = msprime.sim_ancestry(
  File "/home/peter/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1181, in sim_ancestry
    sim = _parse_sim_ancestry(
  File "/home/peter/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 973, in _parse_sim_ancestry
    raise ValueError(
ValueError: Population names in the input demography and the initial state population table must be equal: pop_0 ≠ p0
```

I'm not clear yet if this is a problem with SLiM, with tskit udpates, or with stdpopsim.

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #1140.

### CODE REVIEW

**Comment by petrelharp** [comment]
OH!!! You are pulling it from *my* fork, whose main branch is TOTALLY not up to date. And, it's pulling from `master`! Ack!! Those quotes in the file names were removed long ago.

**Comment by petrelharp** [comment]
Hm, now failing with:
```
  Attempting uninstall: demes
    Found existing installation: demes 0.2.1
    Uninstalling demes-0.2.1:
      Successfully uninstalled demes-0.2.1
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-uninstall-yvay_t35\\demes.exe'
Consider using the `--user` option or check the permissions.
```
I have no idea what's going on here.

**Comment by petrelharp** [comment]
I have no idea what's going on here *but* the tests pass on linux/macos - I think we can merge this and sort out the windows test issues separately.

**Comment by petrelharp** [comment]
However, we should change the github version of pyslim to a release when I get that out (tomorrow?).

**Comment by grahamgower** [comment]
> OH!!! You are pulling it from _my_ fork, whose main branch is TOTALLY not up to date. And, it's pulling from `master`! Ack!! Those quotes in the file names were removed long ago.

That's weird, I asked it to pull from the `release` branch, not master. I guess `pip install git+foo` doesn't behave how I expected.

> Hm, now failing with:
> 
> ```
>   Attempting uninstall: demes
>     Found existing installation: demes 0.2.1
>     Uninstalling demes-0.2.1:
>       Successfully uninstalled demes-0.2.1
> ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-uninstall-yvay_t35\\demes.exe'
> Consider using the `--user` option or check the permissions.
> ```
> 
> I have no idea what's going on here.

Yeah, I have no idea either. Its a temp dir and the CI already just installed the file there, so it should have permission. I *think* its trying to uninstall demes 0.2.1 to install demes 0.2.0 because that is in our reqiurements file. So bumping the version in the requirements file might paper over the problem.

> However, we should change the github version of pyslim to a release when I get that out (tomorrow?).

Yep. I don't think we need to merge this pr in a hurry, so I'm happy to wait until you release the new pyslim.

**Comment by petrelharp** [comment]
Okay - let's squash these commits and put the pyslim back to the stable release?

**Comment by petrelharp** [comment]
This now passes all tests locally for me!

**Comment by petrelharp** [comment]
Ok, I think we can squash & merge this; to be followed by #1152.

**Pull request merged**
