### PR TITLE
Basic changes for pytest

### PR DESCRIPTION
**Pull request by jeromekelleher**
Ping @grahamgower. The plan is to make the smallest update we can here, and then transition the code over to use pytest features over time.

One thing I was confused about was all the stuff around running coverage. Is that needed now?

### CODE REVIEW

**Comment by grahamgower** [comment]
> One thing I was confused about was all the stuff around running coverage. Is that needed now?

No, those lines can be removed. To get the equivalent output from `pytest`, you can use the `term-missing` coverage report. E.g. see the pytest line in the demes-python repo: https://github.com/popsim-consortium/demes-python/blob/main/.github/workflows/tests.yml#L55-L56

**Comment by grahamgower** [comment]
We could upload the codecov report from the `tests.yml` action too. Then we could remove Circle CI (it's equally difficult to manage as github actions, so having both is just maintenance burden).

**Comment by jeromekelleher** [comment]
> We could upload the codecov report from the tests.yml action too. Then we could remove Circle CI (it's equally difficult to manage as github actions, so having both is just maintenance burden).

Sure - feel free to file an issue to track. I don't want to get too deep down CI rabbit holes here though.

**Comment by jeromekelleher** [comment]
Finally! Jeez that was painful. @grahamgower, can you take a quick look please?

I don't know about you, but I'm not particularly worried about the coverage drop.

**Review by grahamgower — APPROVED** [review]
LGTM! You're also closing #708 here.

**Pull request merged**
