### PR TITLE
Update genetic maps URLs to use AWS

### PR DESCRIPTION
**Pull request by ndukler**

### CODE REVIEW

**Comment by ndukler** [comment]
@jeromekelleher I think this is good to go.

**Comment by jeromekelleher** [comment]
LGTM!

```
$ python3 -m stdpopsim download-genetic-maps                                                       
INFO:stdpopsim.genetic_maps:Downloading genetic map 'HapMapII_GRCh37' from https://stdpopsim.s3-us-west-2.amazonaws.com/genetic_maps/HomSap/HapmapII_GRCh37_RecombinationHotspots.tar.gz
INFO:stdpopsim.genetic_maps:Storing map in /home/jk/.cache/stdpopsim/genetic_maps/HomSap/HapMapII_GRCh37
INFO:stdpopsim.genetic_maps:Downloading genetic map 'DeCodeSexAveraged_GRCh36' from https://stdpopsim.s3-us-west-2.amazonaws.com/genetic_maps/HomSap/decode_2010_sex-averaged_map.tar.gz
INFO:stdpopsim.genetic_maps:Storing map in /home/jk/.cache/stdpopsim/genetic_maps/HomSap/DeCodeSexAveraged_GRCh36
INFO:stdpopsim.genetic_maps:Downloading genetic map 'SalomeAveraged_TAIR7' from https://stdpopsim.s3-us-west-2.amazonaws.com/genetic_maps/AraTha/salome2012_maps.tar.gz
INFO:stdpopsim.genetic_maps:Storing map in /home/jk/.cache/stdpopsim/genetic_maps/AraTha/SalomeAveraged_TAIR7
INFO:stdpopsim.genetic_maps:Downloading genetic map 'ComeronCrossover_dm6' from https://stdpopsim.s3-us-west-2.amazonaws.com/genetic_maps/DroMel/comeron2012_maps.tar.gz
INFO:stdpopsim.genetic_maps:Storing map in /home/jk/.cache/stdpopsim/genetic_maps/DroMel/ComeronCrossover_dm6
INFO:stdpopsim.genetic_maps:Downloading genetic map 'Campbell2016_CanFam3_1' from https://stdpopsim.s3-us-west-2.amazonaws.com/genetic_maps/CanFam/dog_genetic_maps.tar.gz
INFO:stdpopsim.genetic_maps:Storing map in /home/jk/.cache/stdpopsim/genetic_maps/CanFam/Campbell2016_CanFam3_1
```
and then
```
$ tree  ~/.cache/stdpopsim/       
/home/jk/.cache/stdpopsim/                           
└── genetic_maps                                     
    ├── AraTha                                       
    │   └── SalomeAveraged_TAIR7                     
    │       ├── arab_chr1_map_loess.txt             
    │       ├── arab_chr2_map_loess.txt    
    │       ├── arab_chr3_map_loess.txt    
    │       ├── arab_chr4_map_loess.txt    
    │       ├── arab_chr5_map_loess.txt                       
    │       └── convertMapToRates.R                           
    ├── CanFam                                                
    │   └── Campbell2016_CanFam3_1                            
    │       ├── chr10_average_canFam3.1.txt                   
     [snipped]
    ├── DroMel
    │   └── ComeronCrossover_dm6
    │       ├── genetic_map_comeron2012_dm6_chr2L.txt
    │       ├── genetic_map_comeron2012_dm6_chr2R.txt
    │       ├── genetic_map_comeron2012_dm6_chr3L.txt
    │       ├── genetic_map_comeron2012_dm6_chr3R.txt
    │       ├── genetic_map_comeron2012_dm6_chrX.txt
    │       └── README_Comeron2012_dm6
    └── HomSap
        ├── DeCodeSexAveraged_GRCh36
        │   ├── genetic_map_decode_2010_sex-averaged_chr10.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr11.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr12.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr13.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr14.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr15.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr16.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr17.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr18.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr19.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr1.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr20.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr21.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr22.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr2.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr3.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr4.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr5.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr6.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr7.txt
        │   ├── genetic_map_decode_2010_sex-averaged_chr8.txt
        │   └── genetic_map_decode_2010_sex-averaged_chr9.txt
        └── HapMapII_GRCh37
            ├── genetic_map_GRCh37_chr10.txt
            ├── genetic_map_GRCh37_chr11.txt
            ├── genetic_map_GRCh37_chr12.txt
            ├── genetic_map_GRCh37_chr13.txt
            ├── genetic_map_GRCh37_chr14.txt
            ├── genetic_map_GRCh37_chr15.txt
            ├── genetic_map_GRCh37_chr16.txt
            ├── genetic_map_GRCh37_chr17.txt
            ├── genetic_map_GRCh37_chr18.txt
            ├── genetic_map_GRCh37_chr19.txt
            ├── genetic_map_GRCh37_chr1.txt
            ├── genetic_map_GRCh37_chr20.txt
            ├── genetic_map_GRCh37_chr21.txt
            ├── genetic_map_GRCh37_chr22.txt
            ├── genetic_map_GRCh37_chr2.txt
            ├── genetic_map_GRCh37_chr3.txt
            ├── genetic_map_GRCh37_chr4.txt
            ├── genetic_map_GRCh37_chr5.txt
            ├── genetic_map_GRCh37_chr6.txt
            ├── genetic_map_GRCh37_chr7.txt
            ├── genetic_map_GRCh37_chr8.txt
            ├── genetic_map_GRCh37_chr9.txt
            ├── genetic_map_GRCh37_chrX_par1.txt
            ├── genetic_map_GRCh37_chrX_par2.txt
            ├── genetic_map_GRCh37_chrX.txt
            └── README_hapmapII_GRCh37_map
```

**Comment by jeromekelleher** [comment]
Woohoo, living in the future! Great work @ndukler, thanks a million for getting this done!

**Comment by ndukler** [comment]
Eh, I've been horribly unreliable lately so this was the least I could do. Sorry :(

**Pull request merged**
