### PR TITLE
add AJ model

### PR DESCRIPTION
**Pull request by agladstein**
This PR is in response to https://github.com/popsim-consortium/stdpopsim/issues/491

Not ready to be merged.

### CODE REVIEW

**Comment by apragsdale** [comment]
Hi @agladstein, that looks good so far. There are a few other components to include.. I think the main one is adding a parameter table in docs/parameter_tables/ which ensures that the parameters are displayed in the documentation.

I think at this point, you don't have to worry about setting up the equivalency tests with a QC model, because whoever does the QCing will add those tests. I don't think anything else is missing, and the model looks well documented.

**Comment by agladstein** [comment]
I'm still confused about how it gets incorporated. It does show up in `species.demographic_models()`

**Comment by grahamgower** [comment]
That looks like it should be pulled in to the catalog just fine. Maybe you're 'import'ing a stdpopsim that isn't your development folder?

It looks like one of the unit tests in the CI is complaining about "Demographic events must be time sorted.". So I'm pretty sure your model is getting pulled into the catalog. (The time sorting won't prevent you from seeing the model in the catalog, but it will prevent you from simulating it.

**Comment by agladstein** [comment]
I have not added unit tests yet. Waiting on https://github.com/popsim-consortium/stdpopsim/issues/305

There are two funny things about this model. 
1. The model parameters were inferred with ABC, and because there were so many and we didn't care about all of them, we left a few parameters as "free" parameters and did not infer them. I've noted those parameters in the model function as comments and how I'm handling them here.
2. Simulations were originally done with 2.5e-8 mutation rate. For now, I've noted that in the long description.

Dan and I also talked about adding priors as a feature to stdpopsim - and this would be a good model to use for that. So, maybe it's better to implement this model once we have a priors feature and we don't deal with the issue of including parameters that weren't inferred in the paper.

**Comment by grahamgower** [comment]
Hey @agladstein, this looks like it's in pretty good shape. CircleCI is just complaining about some spaces at the ends of lines in your `long_description`. If you fix that, I think this will be good to merge.

**Comment by agladstein** [comment]
fixed it.

**Comment by jeromekelleher** [comment]
Can you merge if you're happy please @grahamgower?

**Comment by grahamgower** [comment]
Merged in. Thanks @agladstein!

**Pull request merged**
