### PR TITLE
More validation.

### PR DESCRIPTION
**Pull request by grahamgower**

### CODE REVIEW

**Comment by grahamgower** [comment]
The attached results are with #440 applied and using 240 replicates for each scenario. The pairwise population statistics look off for AncientEurasia_9K19, but I don't see anything else too concerning.

[Africa_1T12_msprime1__Africa_1T12_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380641/Africa_1T12_msprime1__Africa_1T12_slim1.pdf)
[AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380642/AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf)
[AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380643/AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380644/onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380645/onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380646/onepop_constantN_msprime1__onepop_constantN_slim1.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380647/onepop_constantN_msprime1__onepop_constantN_slim2.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380648/onepop_constantN_msprime1__onepop_constantN_slim3.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380649/onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380650/onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380651/onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf)
[OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380652/OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380653/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380654/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380655/twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380656/twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380657/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4380658/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf)

**Comment by grahamgower** [comment]
Oh, btw, the linkage disequilibrium QQ plots are not as helpful as I'd hoped, because there is often too few segregating sites to contribute to one of the R^2 bins created here. I have a threshold for the number of observations per bin, which helps in some cases, but in other cases this just biases the statistic. Probably we need to increase the mutation rate to more meaningfully evaluate LD.

**Comment by jeromekelleher** [comment]
AncientEurasia_9K19 does look slightly off to me - the ts properties look systematically different. Is there anything different that's being done here that isn't in the other models (maybe ancient samples or something)?

**Comment by grahamgower** [comment]
Yeah, ancient samples are the first thing I thought of too. I need to make a simple model with ancient sampling for testing that.

**Comment by jeromekelleher** [comment]
Hmm, looks like there's systematic differences in the ts stats in lots of cases. Is this something to worry about or not? The mutation stats look fine, so perhaps there's nothing to worry about. Are the tree sequences fully simplified, etc? Maybe we're keeping unary nodes around and that's leading to systematic differences between the ts topologies? This wouldn't explain the differences in the number of sites in a lot of the cases.

Systematic differences like this make me nervous, it would be good to have an explanation for *why* we're seeing them. If they turn out to be harmless, then perhaps we should just drop the ts plots them from the comparisons.

**Comment by jeromekelleher** [comment]
Fantastic work btw @grahamgower, this is good to merge whenever.

**Comment by grahamgower** [comment]
In all the `slim1` scenarios, I've used default parameters, which is to scale time by 10. I think this is causing the systematic reduction for at least num_nodes, but probably other properties. There are just 10 times fewer time points for any node to correspond to. If you look at the `slim2` scenarios, which are without recapitation and without time scaling, then the ts properties look better (except num_sites!).

I'm happy for this to get merged. I'll follow up with more specific tests for ancient samples, or anything else I think of for investigating the AncientEurasia_9K19 differences.

**Comment by jeromekelleher** [comment]
OK, let's merge then. Can you follow up with some issues for the things that need to be resolved please?

**Pull request merged**
