### PR TITLE
Improve tooling around adding species.

### PR DESCRIPTION
**Pull request by jeromekelleher**
A bunch of changes around the process of adding a new species. Hopefully this will make clearer what needs to be done by the original implementers and the follow-up QC.

I'll open a PR for mus_musculus so we can see roughly what it looks like. (now open in #797)

### CODE REVIEW

**Review by andrewkern — COMMENTED** [review]
this looks good @jeromekelleher. one question i had when reviewing the earlier version of this code last night is is there a way to autopopulate some of the citations? e.g., does ensembl give references for their assemblies?

if not would it be worth `add-species` creating a blank citation template?

**Comment by jeromekelleher** [comment]
I don't think we'll be able to get citation data from Ensembl, but yes, adding a citation template for the essential stuff would be useful.

**Comment by grahamgower** [comment]
> @grahamgower, any objections to me changing the "x_citations" stuff to a single citations list with `reasons`? It really doesn't make sense having the separate lists, and might as well get it right while we're setting the template for new additions here.

No, that seems reasonable. If there was a reason these were in separate lists, I don't recall what it was.

**Comment by jeromekelleher** [comment]
OK, done. I think this is ready to go if you want to merge @andrewkern. Hopefully you have what you need for writing the basic directions.

**Comment by andrewkern** [comment]
LGTM @jeromekelleher. do you want to squash?

**Review by andrewkern — APPROVED** [review]

**Comment by jeromekelleher** [comment]
Na, these are logically separate commits, merge away (I'm on baby duty)

**Pull request merged**
