### PR TITLE
Require msprime >= 1.0.0a4.

### PR DESCRIPTION
**Pull request by grahamgower**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I don't think this works unfortunately - you'll need to install msprime separately during CI using ``pip install --pre``. Otherwise you'll have to pip install everything ``--pre``, which could result in all sorts of junk being pulled in.

Communicating with developers that they need to have msprime 1.0 installed is probably the simplest approach.

**Comment by grahamgower** [comment]
Hmm, ok. I seem to recall one can put pip command line params inside a requirements.txt file, so maybe that's an option?

**Comment by jeromekelleher** [comment]
Sure, whatever works.

**Comment by grahamgower** [comment]
Well, just specifying `>=1.0.0a3` seems to work for me with the latest pip:
```
$ grep msprime requirements/development.txt
msprime>=1.0.0a3
$ pip install -r requirements/development.txt
<snip>
$ pip show msprime
Name: msprime
Version: 1.0.0a3
Summary: A fast and accurate coalescent simulator.
Home-page: https://pypi.org/project/msprime/
Author: Tskit Developers
Author-email: admin@tskit.dev
License: GNU GPLv3+
Location: /home/grg/.local/lib/python3.9/site-packages
Requires: numpy, tskit, newick
Required-by: pyslim, stdpopsim
```

**Comment by jeromekelleher** [comment]
OK, great. Thanks for introducing me to ``pip show``!

**Pull request closed without merging**
