### PR TITLE
QC PapAnu

### PR DESCRIPTION
**Pull request by mufernando**
I completed all QC steps as described in #1217 

Already talked to @saurabhbelsare and he fixed some issues in a previous PR #1262

### CODE REVIEW

**Comment by saurabhbelsare** [comment]
Could you add the comment about the recombination rates for chromosomes being the unweighted averages in species.py? Thanks!

**Comment by petrelharp** [comment]
Mark this as not a draft when you're ready, @mufernando.

**Comment by petrelharp** [comment]
Closes #1217

**Comment by petrelharp** [comment]
Looks good! Thanks a bunch!

**Pull request merged**
