### PR TITLE
PonAbe QC and assembly update

### LINKED ISSUE #544: QC for PonAbe
The **PonAbe** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [x] Population size.
- [ ] Generation time.

### LINKED ISSUE #595: PonAbe: genetic maps NaterPP_PonAbe2 and NaterPA_PonAbe2 can't be loaded
**Short description of the problem:**
The two orangutan genetic maps are not compatible with msprime's `read_hapmap()` funtion, because the final rate in each file is non-zero.

**How to reproduce the problem:**
```
$ stdpopsim PonAbe -g NaterPP_PonAbe2 10 -o /dev/null
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 33, in <module>
    sys.exit(load_entry_point('stdpopsim', 'console_scripts', 'stdpopsim')())
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 663, in stdpopsim_main
    run(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 654, in run
    args.runner(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 442, in run_simulation
    contig = species.get_contig(
  File "/home/grg/src/stdpopsim/stdpopsim/species.py", line 163, in get_contig
    recomb_map = gm.get_chromosome_map(chrom.id)
  File "/home/grg/src/stdpopsim/stdpopsim/genetic_maps.py", line 152, in get_chromosome_map
    ret = msprime.RecombinationMap.read_hapmap(map_file)
  File "/home/grg/.local/lib/python3.8/site-packages/msprime/simulations.py", line 849, in read_hapmap
    raise ValueError(
ValueError: The last rate provided in the recombination map must zero
```

**Suggested fixes:**
Append a new line to each genetic map file which consists of the chromosome length and rate=0.

### LINKED ISSUE #1249: ZeroDivisionError during PonAbe liftover
Get necessary files.
```
$ wget https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOver
$ wget https://hgdownload.soe.ucsc.edu/goldenPath/ponAbe3/liftOver/ponAbe3ToPonAbe2.over.chain.gz
$ wget https://hgdownload.soe.ucsc.edu/goldenPath/ponAbe2/liftOver/ponAbe2ToPonAbe3.over.chain.gz
```
Be sure to `chmod +x liftOver` and put it in your `$PATH`. Then try the `liftOver_catalog.py` script as outlined in the dev docs.

```
$ python maintenance/liftOver_catalog.py \
  --species PonAbe \
  --map NaterPA_PonAbe2 \
  --chainFile ponAbe2ToPonAbe3.over.chain.gz \
  --validationChain ponAbe3ToPonAbe2.over.chain.gz \
  --winLen 1000 \
  --gapThresh 1000000 \
  --useAdjacentAvg \
  --retainIntermediates

Downloading tarball...
Extracting tarball...

Mapping the rates to the new assembly...
Reading liftover chains
Mapping coordinates
Reading liftover chains
Reading liftover chains
Mapping coordinates
Mapping coordinates
Reading liftover chains
Reading liftover chains
Mapping coordinates
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Reading liftover chains
Mapping coordinates
Mapping coordinates
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/grg/src/stdpopsim/maintenance/liftOver.py", line 561, in worker
    joinedRates, new_average = bed_to_hapmap(
  File "/home/grg/src/stdpopsim/maintenance/liftOver.py", line 143, in bed_to_hapmap
    rescaled_rate = rescale_rate(oldRateDict, ar)
  File "/home/grg/src/stdpopsim/maintenance/liftOver.py", line 124, in rescale_rate
    float(ar[3]) * (old_interval[1] - old_interval[0]) / (int(ar[2]) - int(ar[1]))
ZeroDivisionError: float division by zero
```

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #544.
Closes #595.
Closes #1249.

### CODE REVIEW

**Comment by grahamgower** [comment]
Does these changes look ok to you @apragsdale?

The lifted-over recombination maps still need to be uploaded to AWS. I think @andrewkern shared the AWS keys with me a while back so I'll check if I can do this myself.

**Comment by petrelharp** [comment]
So - is the conclusion that it looks good to you, @apragsdale?

**Review by petrelharp — APPROVED** [review]
Looks good! I don't see any issues.

**Review by apragsdale — APPROVED** [review]

**Comment by petrelharp** [comment]
Thanks a bunch!!!

**Pull request merged**
