### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by grahamgower**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM, let me know when you want to merge.

**Comment by grahamgower** [comment]
What's going on with circle CI? Did I do something wrong with branches here?

**Comment by jeromekelleher** [comment]
Branching looks fine I think. Are the tests passing locally for you?

**Comment by grahamgower** [comment]
Yeah, tests are fine locally. This PR doesn't even touch anything that's tested though.

**Comment by grahamgower** [comment]
Validation plots attached, which were run with #446. Please merge if you're happy.
```
$ time ./validation.py -j 80 -r 240
...
real    22m56.305s
user    1385m26.686s
sys     143m18.855s
```

[Africa_1T12_msprime1__Africa_1T12_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388204/Africa_1T12_msprime1__Africa_1T12_slim1.pdf)
[AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388205/AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf)
[AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388206/AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388207/onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388208/onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388209/onepop_bottleneck_msprime1__onepop_bottleneck_slim3.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388210/onepop_constantN_msprime1__onepop_constantN_slim1.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388211/onepop_constantN_msprime1__onepop_constantN_slim2.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388212/onepop_constantN_msprime1__onepop_constantN_slim3.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388213/onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388214/onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388215/onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf)
[OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388216/OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf)
[twopop_ancient_samples_msprime1__twopop_ancient_samples_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388217/twopop_ancient_samples_msprime1__twopop_ancient_samples_slim1.pdf)
[twopop_ancient_samples_msprime1__twopop_ancient_samples_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388219/twopop_ancient_samples_msprime1__twopop_ancient_samples_slim2.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388220/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388221/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388222/twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388223/twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388224/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4388225/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf)

**Comment by jeromekelleher** [comment]
We'll need to figure out why circle is failing first...

**Comment by grahamgower** [comment]
I reused my previous `validation` branch here. Maybe there's some state associated with that which is not correctly being discarded by the github/circle integration.

**Comment by andrewkern** [comment]
not sure we want to deal with this here, but why are the onepop_expgrowth looking so different?

**Comment by grahamgower** [comment]
The min(tmrca) looks a bit funny---is that what you're referring to? The tree sequence properties like num_edges, num_nodes, and num_sites are off for most of the comparisons, and I have opened #434 and #444 about these.

**Comment by andrewkern** [comment]
nodes and sites on this one: https://github.com/popsim-consortium/stdpopsim/files/4388215/onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf

**Comment by grahamgower** [comment]
Squashed and rebased.

**Pull request merged**
