### PR TITLE
Add an example of user-specified mutation rates

### PR DESCRIPTION
**Pull request by hyanwong**
Partially addresses #530. Not sure if the formatting is correct

### CODE REVIEW

**Comment by grahamgower** [comment]
LGTM! Just a small lint issue to be taken care of.

contig-docs

**Comment by apragsdale** [comment]
Awesome, thanks @hyanwong!! I think this is a really important flexibility that wasn't previously supported. Really appreciate it.

**Comment by hyanwong** [comment]
No problem. It's useful for me.

I corrected the lint error, but now there's some odd error in CI. What do I need to do, @grahamgower ?

**Comment by andrewkern** [comment]
looks like it needs to be linted 

> #!/bin/bash -eo pipefail
flake8 --max-line-length 89 stdpopsim setup.py tests docs/_ext maintenance

maybe rebase and run flake?

**Comment by hyanwong** [comment]
> looks like it needs to be linted
> 
> > #!/bin/bash -eo pipefail
> > flake8 --max-line-length 89 stdpopsim setup.py tests docs/_ext maintenance
> 
> maybe rebase and run flake?

I'm getting:

```
#!/bin/sh -eo pipefail
# Orb codecov/codecov@1.1.1 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.
```

But maybe that's just my setup masking the real error.

**Comment by hyanwong** [comment]
Seems OK on my end.

```
flake8 --max-line-length 89 stdpopsim setup.py tests docs/_ext maintenance
```

Gives no errors for me on this branch.

**Comment by andrewkern** [comment]
weird. guessing this has to do with #620. doesn't look like you are rebased against master though, so maybe that will fix this?

**Comment by grahamgower** [comment]
Yeah, that is weird, because @petrelharp enabled that orb feature a few days ago. Has it been turned off somehow?

**Comment by petrelharp** [comment]
It appears so? I'll see what I can do.
Screenshot from 2020-10-19 11-07-00

**Comment by petrelharp** [comment]
Oh! I see! This is actually running on @hyanwong's CircleCI account, for some reason??? When i click on the "Details" link for CircleCI, I see the error above, and on the left is an "Organisation Settings" link that leads to ... settings for the "hyanwong" organization. So maybe @hyanwong needs to do this? Let us know if that does it - we don't want to make everyone submitting PRs go through that, I think...

**Comment by hyanwong** [comment]
Ah - I have never actually done this. It's a pain that it needs doing though, surely? Should I even have to set up a circleCI account to submit a PR? I just clicked though a couple of steps, ISTR. I'd prefer to just delete my circleCI account if possible - too confusing having all these separate accounts on different sites.

**Comment by hyanwong** [comment]
aaand - annoyingly although I can turn on the 3rd part orbs thing, I can't actually force a rerun of CI (it's greyed out) for this PR. I'll have to make some trivial change or something and push.

**Comment by petrelharp** [comment]
Huh, it said I couldn't force a rebuild either, since it was your organization?

Maybe @platipo knows what's going on here?

**Comment by hyanwong** [comment]
Well, I amended a change and force pushed, which has got it to re-run. But it's not been an easy journey just to make a doc change.

**Comment by andrewkern** [comment]
and it looked like it now passes the build tests!

**Pull request merged**
