### PR TITLE
refactor of DFE CLI tests

### PR DESCRIPTION
**Pull request by petrelharp**
I was working on tracking down #1162, and in the process refactored the DFE CLI tests (so I could isolate where it was happening). I would also like to make this test faster, but I cannot figure out how to do it - [`test_dfe_annotation`](https://github.com/popsim-consortium/stdpopsim/pull/1169/files#diff-b201385bdd9318912fe29722d750c1d4007aa5fa1454b0d8328eb6cba68dcdadR366) needs to simulate a whole chromosome (to use an annotation), and the scaling factor can't be bigger than about 20 (or else we hit the #1162 error). Unless perhaps we can use
```
  -i INCLUSION_MASK, --inclusion-mask INCLUSION_MASK
                        Path to inclusion mask specified in bed format.
```
to speed things up - I haven't tried yet. Does anyone else know, or have good ideas?

### CODE REVIEW

**Comment by grahamgower** [comment]
I guess we could add an (undocumented) species just for testing this kind of thing. But maybe we just need annotations for more species, particularly one with really short chromosomes?

**Comment by petrelharp** [comment]
Well, we do kinda want to be able to test the annotations of long chromosomes, sometimes? If we had an easy way to run a simulation with a very small `N`, that would work as well?

**Comment by grahamgower** [comment]
Sure. That could also be accomplished by adding a species that's just for tests.

**Comment by petrelharp** [comment]
Using the inclusion mask does *not* speed things up.

**Comment by petrelharp** [comment]
Could you have a look at this now, @izabelcavassim? I have not solved the problem of making the tests run faster, but I'd like to merge this much in anyhow.

(Note: I also tried chr4 from DroMel... but it takes FOREVER even though it's so small...)

**Comment by izabelcavassim** [comment]
Thinking here, when we use the DFE annotation, do we really need to use the whole chromosome? Because we could also say I want annotation ranging from X-Y in that given contig. By doing this slice would we be losing the main feature of the DFE-annotation? @petrelharp ?

**Comment by petrelharp** [comment]
> Thinking here, when we use the DFE annotation feature, do we really need to use the whole chromosome? Because we could also say I want annotation ranging from X-Y in that given contig. By doing this slice would we be losing the main feature of the DFE-annotation?

This is what I was going for in trying the inclusion mask. However, I didn't track down what exactly `--inclusion-mask` is doing: it seems like (from runtime) it is simulating the whole chromosome (I remember we discussed this but don't remember the conclusion).

**Comment by grahamgower** [comment]
From memory, the mask is applied by chopping into the tree sequence post simulation. But @apragsdale will remember the details.

**Comment by petrelharp** [comment]
Have you had a look at the code, @izabelcavassim - can we merge this?

**Comment by izabelcavassim** [comment]
> Have you had a look at the code, @izabelcavassim - can we merge this?

Yes, from what I see it is all fine! LGTM!

**Pull request merged**
